// examples/react-app.jsx
/**
 * React example
 * This is a reference implementation for React applications
 */

import React, { useState } from "react";
import { toWords } from "number-to-words-id";

export default function NumberToWordsConverter() {
  const [num, setNum] = useState("1234");
  const [lang, setLang] = useState("id");
  const [currency, setCurrency] = useState("");
  const [type, setType] = useState("cardinal");
  const [result, setResult] = useState("");

  const handleConvert = () => {
    try {
      const options = { lang, type };
      if (currency) options.currency = currency;

      const words = toWords(num, options);
      setResult(words);
    } catch (error) {
      setResult(`Error: ${error.message}`);
    }
  };

  return (
    <div style={{ padding: "20px", maxWidth: "600px", margin: "0 auto" }}>
      <h1>Number to Words Converter</h1>

      <div style={{ marginBottom: "15px" }}>
        <label style={{ display: "block", marginBottom: "5px" }}>
          Number:
        </label>
        <input
          type="text"
          value={num}
          onChange={(e) => setNum(e.target.value)}
          style={{ width: "100%", padding: "8px" }}
          placeholder="Enter number"
        />
      </div>

      <div style={{ marginBottom: "15px" }}>
        <label style={{ display: "block", marginBottom: "5px" }}>
          Language:
        </label>
        <select
          value={lang}
          onChange={(e) => setLang(e.target.value)}
          style={{ width: "100%", padding: "8px" }}
        >
          <option value="id">Indonesian</option>
          <option value="en">English</option>
          <option value="ms">Malaysian</option>
        </select>
      </div>

      <div style={{ marginBottom: "15px" }}>
        <label style={{ display: "block", marginBottom: "5px" }}>
          Type:
        </label>
        <select
          value={type}
          onChange={(e) => setType(e.target.value)}
          style={{ width: "100%", padding: "8px" }}
        >
          <option value="cardinal">Cardinal</option>
          <option value="ordinal">Ordinal</option>
        </select>
      </div>

      <div style={{ marginBottom: "15px" }}>
        <label style={{ display: "block", marginBottom: "5px" }}>
          Currency (optional):
        </label>
        <input
          type="text"
          value={currency}
          onChange={(e) => setCurrency(e.target.value)}
          style={{ width: "100%", padding: "8px" }}
          placeholder="e.g., IDR, USD, MYR"
        />
      </div>

      <button
        onClick={handleConvert}
        style={{
          padding: "10px 20px",
          backgroundColor: "#007bff",
          color: "white",
          border: "none",
          borderRadius: "4px",
          cursor: "pointer",
        }}
      >
        Convert
      </button>

      {result && (
        <div
          style={{
            marginTop: "20px",
            padding: "15px",
            backgroundColor: "#f8f9fa",
            borderRadius: "4px",
            border: "1px solid #dee2e6",
          }}
        >
          <strong>Result:</strong>
          <p style={{ margin: "10px 0 0 0", fontSize: "18px" }}>{result}</p>
        </div>
      )}
    </div>
  );
}

// examples/vue-app.vue
<!--
  Vue 3 example
  This is a reference implementation for Vue 3 applications
-->

<script setup>
import { ref } from "vue";
import { toWords } from "number-to-words-id";

const num = ref("1234");
const lang = ref("id");
const currency = ref("");
const type = ref("cardinal");
const result = ref("");

function convert() {
  try {
    const options = { lang: lang.value, type: type.value };
    if (currency.value) options.currency = currency.value;

    result.value = toWords(num.value, options);
  } catch (error) {
    result.value = `Error: ${error.message}`;
  }
}
</script>

<template>
  <div class="converter">
    <h1>Number to Words Converter</h1>

    <div class="form-group">
      <label for="number">Number:</label>
      <input
        id="number"
        v-model="num"
        type="text"
        placeholder="Enter number"
      />
    </div>

    <div class="form-group">
      <label for="language">Language:</label>
      <select id="language" v-model="lang">
        <option value="id">Indonesian</option>
        <option value="en">English</option>
        <option value="ms">Malaysian</option>
      </select>
    </div>

    <div class="form-group">
      <label for="type">Type:</label>
      <select id="type" v-model="type">
        <option value="cardinal">Cardinal</option>
        <option value="ordinal">Ordinal</option>
      </select>
    </div>

    <div class="form-group">
      <label for="currency">Currency (optional):</label>
      <input
        id="currency"
        v-model="currency"
        type="text"
        placeholder="e.g., IDR, USD, MYR"
      />
    </div>

    <button @click="convert" class="btn">Convert</button>

    <div v-if="result" class="result">
      <strong>Result:</strong>
      <p>{{ result }}</p>
    </div>
  </div>
</template>

<style scoped>
.converter {
  padding: 20px;
  max-width: 600px;
  margin: 0 auto;
}

.form-group {
  margin-bottom: 15px;
}

.form-group label {
  display: block;
  margin-bottom: 5px;
  font-weight: 500;
}

.form-group input,
.form-group select {
  width: 100%;
  padding: 8px;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 14px;
}

.btn {
  padding: 10px 20px;
  background-color: #42b983;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 16px;
}

.btn:hover {
  background-color: #3aa876;
}

.result {
  margin-top: 20px;
  padding: 15px;
  background-color: #f8f9fa;
  border-radius: 4px;
  border: 1px solid #dee2e6;
}

.result p {
  margin: 10px 0 0 0;
  font-size: 18px;
}
</style>
